### ISSUE TITLE
usage in browser... How?

### ISSUE THREAD

**Issue by jedie** [polyglotted/msgpack-javascript#1]
The README says:

> Single codebase to serve both Browser and Node environments

But how to use it in the browser? There is no "ready-to-use" .js file, isn't it?

btw. Seems that this is one of the most freshest fork of msgpack-javascript, isn't it? What's the difference between msgpack/msgpack-javascript vs. polyglotted/msgpack-javascript ?

**Comment by ahmednuaman** [comment]
If you're planning on using it with webpack then simply install it with npm
and require it, otherwise clone the repo and run `gulp build`.

**Comment by jedie** [comment]
I found https://github.com/uupaa/MessagePack.js

It seems that they has some ready-to-use .js files, for browser use and a example: https://github.com/uupaa/MessagePack.js#browser-and-nwjsnode-webkit

btw. why not merge both projects?!?

**Comment by ahmednuaman** [comment]
We decided to use our own implementation.
